  name: "Codecov Action"
  description: "upload coverage.xml when push or pull request"
  runs:
      using: composite
      steps:
          - run: echo "test start"
            shell: bash
          - run: ${{ github.action_path }}/entrypoint.sh
            shell: bash
